name: Build and Deploy Python Lambda with Layer

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t lambda-layer -f video_slicer/Dockerfile .

      - name: Run Docker container and extract layer.zip
        run: docker run --rm --entrypoint "" -v ${{ github.workspace }}:/output lambda-layer cp /lambda/layer.zip /output/

      - name: Upload layer.zip to S3
        run: aws s3 cp layer.zip s3://${{ env.AWS_BUCKET_NAME }}/lambda_layers/layer.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET_NAME: foodflix-videos
          ############################################ TROCAR DE env PRA secrets

      - name: Publish Lambda Layer
        run: |
          aws lambda publish-layer-version \
            --layer-name py_layer_video_slicer \
            --content S3Bucket=${{ env.AWS_BUCKET_NAME }},S3Key=lambda_layers/layer.zip \
            --compatible-runtimes python3.10
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET_NAME: foodflix-videos
      ############################################ TROCAR DE env PRA secrets

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r video_slicer/requirements.txt

      - name: Package Lambda function
        run: |
          cd video_slicer
          zip -r9 ../video_slicer.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name video_slicer \
            --zip-file fileb://video_slicer.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET_NAME: foodflix-videos